# Default values for jjobs.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  all:
    registry: docker.io
    repository: 'jjobs/jjob-all'
    tag: latest
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  name:

podSecurityContext: {}

securityContext: {}

service:
  name: http
  type: LoadBalancer
  externalPort: 80
  internalPort: 8080
  tls: []

readinessProbe:
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 10
livenessProbe:
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 10

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: jjobs.local
      paths: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
