apiVersion: v1
kind: Secret
metadata:
  name: {{ include "devon-prototype.fullname" . }}-secret-repository
  labels:
    app: {{ template "devon-prototype.name" . }}
    chart: {{ template "devon-prototype.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  url: {{ .Values.devonhome.repository.url | b64enc | quote }}