apiVersion: v1
kind: Secret
metadata:
  name: {{ include "devon-prototype.fullname" . }}-secret-repository
  labels:
{{ include "devon-prototype.labels" . | indent 4 }}
type: Opaque
data:
  url: {{ .Values.devonhome.repository.url | replace "@" "%40" }}