apiVersion: v2
appVersion: "1.0"
description: A Helm chart for DevOn Enterprise
name: devon-enterprise
version: 0.1.0
dependencies:
  - name: redis-ha
    version: 4.4.0
    repository: https://charts.helm.sh/stable
    condition: redis.enabled
  - name: rabbitmq-ha
    version: 1.38.2
    repository: https://charts.helm.sh/stable
  - name: postgresql
    version: 7.1.0
    repository: https://charts.helm.sh/stable
    condition: postgresql.enabled
icon: https://www.lgcns.co.kr/static/images/solution/img_devon_ide_logo.png