dependencies:
  - name: redis-ha
    version: 4.0.3
    repository: https://kubernetes-charts.storage.googleapis.com/
  - name: rabbitmq-ha
    version: 1.36.3
    repository: https://kubernetes-charts.storage.googleapis.com/
  - name: postgresql
    version: 7.1.0
    repository: https://kubernetes-charts.storage.googleapis.com/