apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "jjobs.fullname" . }}-server
  labels:
{{ include "jjobs.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "jjobs.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      deploymentName: {{ include "jjobs.fullname" . }}-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "jjobs.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        deploymentName: {{ include "jjobs.fullname" . }}-server
    spec:
            {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
            {{- toYaml . | nindent 8 }}
            {{- end }}
      serviceAccountName: {{ template "jjobs.serviceAccountName" . }}
      securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 8 }}
      hostname: "jjob-server.local"
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
                {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.server.registry }}/{{ .Values.image.server.repository }}:{{ .Values.image.server.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: tcp
              containerPort: 19000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /jjob-server
              port: 8080
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          readinessProbe:
            httpGet:
              path: /jjob-server
              port: 8080
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            failureThreshold: {{  .Values.readinessProbe.failureThreshold }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
            {{- with .Values.nodeSelector }}
      nodeSelector:
            {{- toYaml . | nindent 8 }}
            {{- end }}
            {{- with .Values.affinity }}
      affinity:
            {{- toYaml . | nindent 8 }}
            {{- end }}
            {{- with .Values.tolerations }}
      tolerations:
          {{- toYaml . | nindent 8 }}
        {{- end }}
