apiVersion: v1
kind: Service
metadata:
  name: {{ include "jjobs.fullname" . }}-agent
  labels:
{{ include "jjobs.labels" . | indent 4 }}
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: {{ include "jjobs.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    deploymentName: {{ include "jjobs.fullname" . }}-agent