apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jjob-all
  labels:
{{ include "jjobs.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "jjobs.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      deploymentName: jjob-all
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "jjobs.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        deploymentName: jjob-all
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ template "jjobs.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: all
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: 10.80.9.3:5000/jjobs/jjob-all:latest
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: JJOB_SERVER_ID
              value: "1-1"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: tcp0
              containerPort: 19000
              protocol: TCP
            - name: tcp1
              containerPort: 19001
              protocol: TCP
            - name: tcp2
              containerPort: 19002
              protocol: TCP
            - name: tcp3
              containerPort: 19003
              protocol: TCP
            - name: tcp4
              containerPort: 19004
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
