# Default values for the chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

image:
  webarchive:
    repository: ananwaresystems/webarchive
    tag: "1.0"
  tomcat:
    repository: lenasupport/lena-exclusive-dev
    tag: "cent7_x86_64-1.3.0e-lab.512"
  pullPolicy: IfNotPresent
  pullSecrets: []

deploy:
  directory: /engn001/lena/1.3/servers/appServer/webapps

service:
  name: http
  type: LoadBalancer
  externalPort: 80
  internalPort: 8180

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - chart-example.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

readinessProbe:
  path: "/"
  initialDelaySeconds: 60
  periodSeconds: 30
  failureThreshold: 6
livenessProbe:
  path: "/"
  initialDelaySeconds: 60
  periodSeconds: 30

resources: {}
#  limits:
#    cpu: 100m
#    memory: 256Mi
#  requests:
#    cpu: 100m
#    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {}

lenaManagerIp: 127.0.0.1

lenaManagerPort: 7700

tunaServerIp: 127.0.0.1
