apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "devon-enterprise.fullname" . }}-logagent
  labels:
{{ include "devon-enterprise.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "devon-enterprise.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      deploymentName: {{ include "devon-enterprise.fullname" . }}-logagent
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "devon-enterprise.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        deploymentName: {{ include "devon-enterprise.fullname" . }}-logagent
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ template "devon-enterprise.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
      - name: logagent
        {{- if .Values.persistentVolumeClaim.enabled }}
        persistentVolumeClaim:
          claimName: {{ include "devon-enterprise.fullname" . }}
        {{ else }}
        emptyDir: {}
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}-logagent
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.logagent.registry }}/{{ .Values.image.logagent.repository }}:{{ .Values.image.logagent.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          - name: http
            containerPort: 8080
            protocol: TCP
          livenessProbe:
            httpGet:
              path: /devon-enterprise-logagent
              port: 8080
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          readinessProbe:
            httpGet:
              path: /devon-enterprise-logagent
              port: 8080
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            failureThreshold: {{  .Values.readinessProbe.failureThreshold }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: logagent
            mountPath: /logs001
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
