apiVersion: v1
kind: Secret
metadata:
  name: {{ include "devon-enterprise.fullname" . }}-secret-redis
  labels:
{{ include "devon-enterprise.labels" . | indent 4 }}
type: Opaque
stringData:
  redis.properties: |
    {{ if .Values.redis.enabled }}
    redis.cloudhost = {{ include "devon-enterprise.fullname" . }}-redis-ha.{{ .Release.Namespace }}.svc.cluster.local
    redis.cloudport = 26379
    redis.pw = {{ index .Values "redis-ha" "redisPassword" }}
    redis.name = redis-master
    {{ else }}
    redis.cloudhost = {{ required "redis.cloudhost is required if redis.enabled = false." .Values.redis.cloudhost }}
    redis.cloudport = {{ required "redis.cloudport is required if redis.enabled = false." .Values.redis.cloudport }}
    redis.pw = {{ required "redis-ha.redisPassword is required if redis.enabled = false." index .Values "redis-ha" "redisPassword" }}
    redis.name = {{ required "redis.name is required if redis.enabled = false." .Values.redis.name }}
    {{ end }}
    {{ if .Values.redis.localhost }}
    redis.localhost = {{ .Values.redis.localhost }}
    {{ else }}
    redis.localhost = {{ include "devon-enterprise.fullname" . }}-redis-ha.{{ .Release.Namespace }}.svc.cluster.local
    {{ end }}
    {{ if .Values.redis.localport }}
    redis.localport = {{ .Values.redis.localport }}
    {{ else }}
    redis.localport = 26379
    {{ end }}
