apiVersion: v1
kind: Secret
metadata:
  name: {{ include "devon-enterprise.fullname" . }}
  labels:
  {{ include "devon-enterprise.labels" . | indent 4 }}
type: Opaque
stringData:
  datasource.properties: |
    datasource.default.driverClass = {{ required "datasource.default.driverClass is required." .Values.datasource.default.driverClass }}
    datasource.default.url = {{ required "datasource.default.url is required." .Values.datasource.default.url }}
    datasource.default.username = {{ required "datasource.default.username is required." .Values.datasource.default.username }}
    datasource.default.password = {{ required "datasource.default.password is required." .Values.datasource.default.password }}

    {{ if .Values.datasource.log.driverClass }}
    datasource.log.driverClass = {{ .Values.datasource.log.driverClass }}
    {{ else }}
    datasource.log.driverClass = {{ .Values.datasource.default.driverClass }}
    {{ end }}
    {{ if .Values.datasource.log.url }}
    datasource.log.url = {{ .Values.datasource.log.url }}
    {{ else }}
    datasource.log.url = {{ .Values.datasource.default.url }}
    {{ end }}
    {{ if .Values.datasource.log.username }}
    datasource.log.username = {{ .Values.datasource.log.username }}
    {{ else }}
    datasource.log.username = {{ .Values.datasource.default.username }}
    {{ end }}
    {{ if .Values.datasource.log.password }}
    datasource.log.password = {{ .Values.datasource.log.password }}
    {{ else }}
    datasource.log.password = {{ .Values.datasource.default.password }}
    {{ end }}

    {{ if .Values.datasource.meta.driverClass }}
    datasource.meta.driverClass = {{ .Values.datasource.meta.driverClass }}
    {{ else }}
    datasource.meta.driverClass = {{ .Values.datasource.default.driverClass }}
    {{ end }}
    {{ if .Values.datasource.meta.url }}
    datasource.meta.url = {{ .Values.datasource.meta.url }}
    {{ else }}
    datasource.meta.url = {{ .Values.datasource.default.url }}
    {{ end }}
    {{ if .Values.datasource.meta.username }}
    datasource.meta.username = {{ .Values.datasource.meta.username }}
    {{ else }}
    datasource.meta.username = {{ .Values.datasource.default.username }}
    {{ end }}
    {{ if .Values.datasource.meta.password }}
    datasource.meta.password = {{ .Values.datasource.meta.password }}
    {{ else }}
    datasource.meta.password = {{ .Values.datasource.default.password }}
    {{ end }}

