apiVersion: v1
kind: Secret
metadata:
  name: {{ include "devon-enterprise.fullname" . }}-secret-datasource
  labels:
{{ include "devon-enterprise.labels" . | indent 4 }}
type: Opaque
stringData:
  datasource.properties: |
    {{  if .Values.postgresql.enabled }}
    datasource.default.driverClass={{ .Values.datasource.default.driverClass }}
    datasource.default.url=jdbc:postgresql://{{ include "devon-enterprise.fullname" . }}-postgresql.{{ .Release.Namespace }}.svc.cluster.local
    datasource.default.username={{ .Values.postgresql.postgresqlUsername }}
    datasource.default.password={{ include "postgresql.password" . }}

    datasource.log.driverClass={{ .Values.datasource.default.driverClass }}
    datasource.log.url=jdbc:postgresql://{{ include "devon-enterprise.fullname" . }}-postgresql.{{ .Release.Namespace }}.svc.cluster.local
    datasource.log.username={{ .Values.postgresql.postgresqlUsername }}
    datasource.log.password={{ include "postgresql.password" . }}

    datasource.meta.driverClass={{ .Values.datasource.default.driverClass }}
    datasource.meta.url=jdbc:postgresql://{{ include "devon-enterprise.fullname" . }}-postgresql.{{ .Release.Namespace }}.svc.cluster.local
    datasource.meta.username={{ .Values.postgresql.postgresqlUsername }}
    datasource.meta.password={{ include "postgresql.password" . }}

    datasource.uat.driverClass={{ .Values.datasource.default.driverClass }}
    datasource.uat.url=jdbc:postgresql://{{ include "devon-enterprise.fullname" . }}-postgresql.{{ .Release.Namespace }}.svc.cluster.local
    datasource.uat.username={{ .Values.postgresql.postgresqlUsername }}
    datasource.uat.password={{ include "postgresql.password" . }}

    {{ else }}
    datasource.default.driverClass={{ required "datasource.default.driverClass is required." .Values.datasource.default.driverClass }}
    datasource.default.url={{ required "datasource.default.url is required." .Values.datasource.default.url }}
    datasource.default.username={{ required "datasource.default.username is required." .Values.datasource.default.username }}
    datasource.default.password={{ required "datasource.default.password is required." .Values.datasource.default.password }}
          {{ if .Values.datasource.log }}
    datasource.log.driverClass={{ required "datasource.log.driverClass is required." .Values.datasource.log.driverClass }}
    datasource.log.url={{ required "datasource.log.url is required." .Values.datasource.log.url }}
    datasource.log.username={{ required "datasource.log.username is required." .Values.datasource.log.username }}
    datasource.log.password={{ required "datasource.log.password is required." .Values.datasource.log.password }}
          {{ else }}
    datasource.log.driverClass={{ .Values.datasource.default.driverClass }}
    datasource.log.url={{ .Values.datasource.default.url }}
    datasource.log.username={{ .Values.datasource.default.username }}
    datasource.log.password={{ .Values.datasource.default.password }}
          {{ end }}
          {{ if .Values.datasource.meta }}
    datasource.meta.driverClass={{ required "datasource.meta.driverClass is required." .Values.datasource.meta.driverClass }}
    datasource.meta.url={{ required "datasource.meta.url is required." .Values.datasource.meta.url }}
    datasource.meta.username={{ required "datasource.meta.username is required." .Values.datasource.meta.username }}
    datasource.meta.password={{ required "datasource.meta.password is required." .Values.datasource.meta.password }}
          {{ else }}
    datasource.meta.driverClass={{ .Values.datasource.default.driverClass }}
    datasource.meta.url={{ .Values.datasource.default.url }}
    datasource.meta.username={{ .Values.datasource.default.username }}
    datasource.meta.password={{ .Values.datasource.default.password }}
          {{ end }}
          {{ if .Values.datasource.uat }}
    datasource.uat.driverClass={{ required "datasource.uat.driverClass is required." .Values.datasource.uat.driverClass }}
    datasource.uat.url={{ required "datasource.uat.url is required." .Values.datasource.uat.url }}
    datasource.uat.username={{ required "datasource.uat.username is required." .Values.datasource.uat.username }}
    datasource.uat.password={{ required "datasource.uat.password is required." .Values.datasource.uat.password }}
          {{ else }}
    datasource.uat.driverClass={{ .Values.datasource.default.driverClass }}
    datasource.uat.url={{ .Values.datasource.default.url }}
    datasource.uat.username={{ .Values.datasource.default.username }}
    datasource.uat.password={{ .Values.datasource.default.password }}
          {{ end }}
    {{ end }}

