{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "devon-enterprise.serviceAccountName" . }}
  labels:
{{ include "devon-enterprise.labels" . | indent 4 }}
{{- end -}}
