apiVersion: v1
kind: Service
metadata:
  name: {{ include "devon-enterprise.fullname" . }}-logagent
  labels:
{{ include "devon-enterprise.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    app.kubernetes.io/name: {{ include "devon-enterprise.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    deploymentName: {{ include "devon-enterprise.fullname" . }}-logagent