apiVersion: v1
kind: Service
metadata:
  name: {{ template "tomcat.fullname" . }}
  labels:
    app: {{ template "tomcat.name" . }}
    chart: {{ template "tomcat.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: {{ .Values.service.name }}
    - name: colletor-tcp
      port: 6100
      targetPort: 6100
      protocol: TCP
    - name: collector-udp
      port: 6100
      targetPort: 6100
      protocol: UDP
  selector:
    app: {{ template "tomcat.name" . }}
    release: {{ .Release.Name }}
